### ISSUE TITLE
please specify the right amount for gentx

### ISSUE THREAD

**Issue by papanomad535** [archway-network/testnets#844]
First intsruction mentioned 1000000000utorii, after that it was changed to 1000000utorii, and the last one is:

archwayd gentx my-key 10000000utorii \
  --commission-rate 0.1 \
  --commission-max-rate 0.1 \
  --commission-max-change-rate 0.1 \
  --pubkey $(archwayd tendermint show-validator --home $HOMEDIR) \
  --chain-id torii-1

https://philabs.notion.site/Configure-your-validator-pre-genesis-6fcdbd34302c489dbd4c2611ebbc63d5

Which one is correct finally?

**Comment by yusufpraditya** [comment]
agree

**Comment by YogaSakti** [comment]
they changed it again?

**Comment by 76Valeriy** [comment]
+

**Comment by YogaSakti** [comment]
![image](https://user-images.githubusercontent.com/24309806/162758997-9fccacf6-f082-4e66-bf5f-260eb1767c7c.png)

**Comment by papanomad535** [comment]
Or not??

> ![image](https://user-images.githubusercontent.com/24309806/162758997-9fccacf6-f082-4e66-bf5f-260eb1767c7c.png)
<img width="762" alt="Снимок экрана 2022-04-11 в 17 25 10" src="https://user-images.githubusercontent.com/65043457/162761023-654797b4-f17c-4524-b93b-1e738753cfe8.png">
